# Generated by Django 4.0.4 on 2022-05-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_publisher_remove_book_publisher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='publisher_id',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_id',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
