# Generated by Django 4.0.4 on 2022-05-21 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_person2_person3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher_id',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='store.publisher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
